\LoadClass[12pt]{extarticle}
\pagenumbering{gobble}

\usepackage{breqn}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{mathtools}

\usepackage{geometry}
\geometry{a4paper, portrait, margin=1in}

\newcommand{\eulerformula}{\begin{gather*}
	\text{By Euler's formula:} \\
	e^{i\theta} = cos(\theta) + i\sin(\theta) \\
	e^{-i\theta} = cos(\theta) - i\sin(\theta)
\end{gather*}}

\newcommand{\degree}{^{\circ}}
\newcommand{\reciprocal}[1]{\frac{1}{#1}}
\newcommand{\rad}{\text{ rad}}
\newcommand{\sig}[1]{\text{ ($#1$ s.f.)}}
